apiVersion: v1
kind: Secret
metadata: 
  name:  mysqlpwd  #不能大写
  namespace: netcore
data:
   mysql_root_password: cGFzc3dvcmQ=   # password的base64位编码
type: Opaque

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: netcore
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    # nodePort: 30306 NodePort模式指定nodePort则使用指定的，不指定则自动生成

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: netcore
spec:
  selector:
    matchLabels: 
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          # value: password 
          valueFrom:   # 在环境变量中使用Secret密码
            secretKeyRef:
              name:  mysqlpwd
              key:  mysql_root_password
        ports:
        - name:  mysql
          containerPort: 3306
        volumeMounts: # mysql内部存储
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: # 外部存储
      - name: mysql-persistent-storage
        hostPath:
          path: /var/lib/mysql
        
